=== scastellotec/ejemploLMSGI/ud2-xsd/conciertos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="fiestaspilar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="concierto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="fechaHora" type="xs:string"/>
                            <xs:element name="ubicacion" type="xs:string"/>
                            <xs:element name="artista" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="10"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>










                            <xs:element name="precio">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:all>
                        <xs:attribute name="id" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scastellotec/ejemploLMSGI/ud2-xsd/conciertos.xml
<?xml version="1.0" encoding="UTF-8"?>
<fiestaspilar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="conciertos.xsd">
    <concierto id="">
        <fechaHora></fechaHora>
        <ubicacion></ubicacion>
        <artista></artista>
        <precio>0</precio>    
    </concierto>
    <concierto id="">
        <artista></artista>
        <ubicacion></ubicacion>
        <fechaHora></fechaHora>
        <precio>0</precio>    
    </concierto>
    <concierto id="">
        <fechaHora></fechaHora>
        <ubicacion></ubicacion>
        <artista></artista>
        <precio>11</precio>    
    </concierto>
    <concierto id="">
        <fechaHora></fechaHora>
        <ubicacion></ubicacion>
        <artista></artista>
        <precio>100</precio>    
    </concierto>
    <concierto id="">
        <fechaHora></fechaHora>
        <ubicacion></ubicacion>
        <artista></artista>
        <precio>5000</precio>    
    </concierto>
</fiestaspilar>
