=== scastellotec/ejemploLMSGI/ud2-xsd/copmany.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="company">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="companyname" type="xs:string"/>
                <xs:element name="address" type="xs:string" minOccurs="0"/>
                <xs:element name="department" maxOccurs="5">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="deptemail" type="xs:string"></xs:element>
                            <xs:element name="employee" minOccurs="0" maxOccurs="10">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="empid">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:ID">
                                                    <xs:maxLength value="3"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="ename">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="32"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="salary">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="10000"/>
                                                    <xs:maxInclusive value="99000"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scastellotec/ejemploLMSGI/ud2-xsd/copmany.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="copmany.xsd">
    <companyname>ABCD</companyname>
    <address>Zaragoza</address>
    <department name="IT345">
        <deptemail>IT@abcd.com</deptemail>
        <employee>
            <empid>e1</empid>
            <ename>pulkit</ename>
            <salary>17200</salary>
        </employee>
    </department>
    <department name="EEE213">
        <deptemail>EEE@abcd.com</deptemail>
    </department>
    <department name="HS012">
        <deptemail>EEE@abcd.com</deptemail>
        <employee>
            <empid>e91</empid>
            <ename>julia maria</ename>
            <salary>27500</salary>
        </employee>
        <employee>
            <empid>e3</empid>
            <ename>andres</ename>
            <salary>32000</salary>
        </employee>
    </department>
</company>
