=== scastellotec/ejemploLMSGI/ud2-xsd/ejemplo_vuelo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aeropuerto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre" type="xs:string"></xs:element>
                <xs:element name="fecha" type="xs:date"></xs:element>
                <xs:element name="vuelos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vuelo" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="origen">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:maxLength value="3"></xs:maxLength>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="destino" type="xs:string"></xs:element>
                                        <xs:element name="hora-salida" type="xs:time"></xs:element>
                                        <xs:element name="hora-llegada" type="xs:time" minOccurs="0"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="codigo" type="xs:ID"></xs:attribute>
                                    <xs:attribute name="estado">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:maxLength value="1"></xs:maxLength>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scastellotec/ejemploLMSGI/ud2-xsd/ejemplo_vuelo.xml
<?xml version="1.0" encoding="UTF-8"?>
<aeropuerto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejemplo_vuelo.xsd">
   <nombre>JFK</nombre>
   <fecha>2023-10-06</fecha>
   <vuelos>
      <vuelo codigo="V22" estado="R">
         <origen>LAX</origen>
         <destino>Chicago</destino>
         <hora-salida>09:30:00</hora-salida>
         <hora-llegada>11:30:00</hora-llegada>
      </vuelo>
      <vuelo codigo="V23" estado="A">
         <origen>JFK</origen>
         <destino>Miami</destino>
         <hora-salida>10:15:00</hora-salida>
      </vuelo>
   </vuelos>
</aeropuerto>
