=== scastellotec/ejemploLMSGI/ud2-xsd/ejemplo0.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aula">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" minOccurs="1" maxOccurs="33">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellido" type="xs:string" minOccurs="1" maxOccurs="2"/>
                        </xs:sequence>
                        <xs:attribute name="num" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== scastellotec/ejemploLMSGI/ud2-xsd/ejemplo0.xml
<?xml version="1.0" encoding="UTF-8"?>
<aula xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejemplo0.xsd">
    <alumno num="1">
        <nombre>José Ramón</nombre>
        <apellido>García</apellido>
    </alumno>
    <alumno num="2">
        <nombre>Carlos</nombre>
        <apellido>López</apellido>
        <apellido>Pérez</apellido>
    </alumno>
    <alumno num="3">
        <nombre>Sara</nombre>
        <apellido>Martín</apellido>
    </alumno>
</aula>
